name: ai_edge_sdk
description: Flutter plugin for Google's AI Edge SDK, enabling on-device generative AI with Gemini Nano on Android devices.
version: 1.0.1
homepage: https://github.com/stefanoamorelli/ai-edge-sdk
repository: https://github.com/stefanoamorelli/ai-edge-sdk
issue_tracker: https://github.com/stefanoamorelli/ai-edge-sdk/issues
documentation: https://github.com/stefanoamorelli/ai-edge-sdk#readme

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tech.amorelli.ai_edge_sdk
        pluginClass: AiEdgeSdkPlugin

topics:
  - artificial-intelligence
  - machine-learning
  - gemini
  - on-device-ai
  - text-generation
